language: c

compiler:
  - gcc

branches:
  only:
    - master

env:
  - NGINX_VERSION=1.10.2
  - NGINX_VERSION=1.10.2 NGINX_DYNAMIC=YES

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y install -qq autotools-dev libexpat-dev libgd2-noxpm-dev libgeoip-dev liblua5.1-dev libmhash-dev libpam0g-dev libpcre3-dev libperl-dev libssl-dev libxslt1-dev zlib1g-dev

install:
  - cd ..
  - wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
  - tar -xf nginx-${NGINX_VERSION}.tar.gz

before_script:
  - mv nginx-sla nginx-${NGINX_VERSION}
  - git clone https://github.com/FRiCKLE/ngx_cache_purge.git nginx-${NGINX_VERSION}/ngx_cache_purge

script:
  - cd nginx-${NGINX_VERSION}
  - test -z "${NGINX_DYNAMIC}" && NGINX_ADD_MODULE=--add-module || NGINX_ADD_MODULE=--add-dynamic-module
  - |
    ./configure \
    --prefix=/usr                                    \
    --conf-path=/etc/nginx/nginx.conf                \
    --http-log-path=/var/log/nginx/access.log        \
    --error-log-path=/var/log/nginx/error.log        \
    --lock-path=/var/lock/nginx.lock                 \
    --pid-path=/run/nginx.pid                        \
    --http-client-body-temp-path=/var/lib/nginx/body \
    --http-fastcgi-temp-path=/var/lib/nginx/fastcgi  \
    --http-proxy-temp-path=/var/lib/nginx/proxy      \
    --http-scgi-temp-path=/var/lib/nginx/scgi        \
    --http-uwsgi-temp-path=/var/lib/nginx/uwsgi      \
    --with-debug                                     \
    --with-pcre-jit                                  \
    --with-ipv6                                      \
    --with-http_ssl_module                           \
    --with-http_stub_status_module                   \
    --with-http_realip_module                        \
    --with-http_auth_request_module                  \
    --with-http_addition_module                      \
    --with-http_dav_module                           \
    --with-http_geoip_module                         \
    --with-http_gzip_static_module                   \
    --with-http_image_filter_module                  \
    --with-http_sub_module                           \
    --with-http_xslt_module                          \
    --with-http_secure_link_module                   \
    ${NGINX_ADD_MODULE}=ngx_cache_purge              \
    ${NGINX_ADD_MODULE}=nginx-sla
  - make
  - sudo make install
